name: Build Setup
description: Install build dependencies and levarage caching.
runs:
  using: composite
  steps:
  - name: Leverage caching
    uses: Swatinem/rust-cache@v2
    with:
      key: x86_64-unknown-linux-gnu
  - name: Install toolchain - nightly
    uses: actions-rs/toolchain@v1
    with:
      toolchain: nightly
      default: true
      components: rustfmt, clippy
  - name: Install linker - mold
    shell: bash
    run: sudo apt install mold
